Add conditional statement for variable declaration
mongodb/mongo pull request #1560
Opened 2023-07-10 08:30 UTC by siddux

The changes solve the minor issue reported [here](https://jira.mongodb.org/browse/CXX-2708).

2023-08-09 09:08 UTC, suenalaba requested changes
good work, some comments

2023-08-09 09:08 UTC, suenalaba commented on src/mongo/util/net/sock.h
> +#ifndef INVALID_SCOKET
```suggestion
#ifndef INVALID_SOCKET
```

spelling error

2023-08-09 09:08 UTC, suenalaba commented on src/mongo/util/net/sock.h
>  typedef int SOCKET;
```suggestion
#endif

typedef int SOCKET;
```

nit: good to add a linebreak, for readability here

2023-08-17 15:47 UTC, siddux commented
Thanks for your comments

2023-08-17 16:32 UTC, kelly-cs commented
Thanks for making this pull request! We just need you to create a new SERVER ticket on [JIRA](https://jira.mongodb.org/) to help us track the PR. Linking https://jira.mongodb.org/browse/CXX-2708 will be great too.

2023-08-18 14:49 UTC, kelly-cs commented
We're changed the existing ticket to [SERVER-80231](https://jira.mongodb.org/browse/SERVER-80231) (originally [CXX-2708](https://jira.mongodb.org/browse/CXX-2708)) to track this work, so no need to make a new ticket.

2023-09-04 18:12 UTC, siddux commented
> > Thanks for your comments
> 
> Please fix he typos and recommit

Just fixed.

2023-09-09 01:26 UTC, suenalaba approved these changes
LGTM.

2024-11-08 23:35 UTC, patrickfreed commented
The mongo codebase isn't intended to be depended upon as a library externally, and there shouldn't be multiple definitions of INVALID_SOCKET internal to mongo. In light of that, I'm going to close this, but thanks for the submission anyways!

2024-11-08 23:35 UTC, closed without merging